function [M11,M12,M21,M22,f1,f2] = autoGen_acrobotDynamics(q1,q2,dq1,dq2,u,m1,m2,g,l1,l2)
%AUTOGEN_ACROBOTDYNAMICS
%    [M11,M12,M21,M22,F1,F2] = AUTOGEN_ACROBOTDYNAMICS(Q1,Q2,DQ1,DQ2,U,M1,M2,G,L1,L2)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    26-Nov-2019 13:44:47

t2 = l1.^2;
M11 = m1.*t2+m2.*t2;
if nargout > 1
    t3 = q1-q2;
    t4 = cos(t3);
    t5 = l1.*l2.*m2.*t4;
    M12 = t5;
end
if nargout > 2
    M21 = t5;
end
if nargout > 3
    M22 = l2.^2.*m2;
end
if nargout > 4
    t6 = sin(t3);
    f1 = g.*l1.*m1.*sin(q1).*2.0+dq2.^2.*l1.*l2.*m2.*t6;
end
if nargout > 5
    f2 = u+g.*l2.*m1.*sin(q2)-dq1.^2.*l1.*l2.*m2.*t6;
end
