function [m,mi,f,fi,mz,mzi,mzd,fz,fzi,fzd] = autoGen_dynSs(q1,q2,q3,dq1,dq2,dq3,u1,u2,m1,m2,m3,l1,l2,l3,g,empty)
%AUTOGEN_DYNSS
%    [M,MI,F,FI,MZ,MZI,MZD,FZ,FZI,FZD] = AUTOGEN_DYNSS(Q1,Q2,Q3,DQ1,DQ2,DQ3,U1,U2,M1,M2,M3,L1,L2,L3,G,EMPTY)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    26-Nov-2019 23:22:56

t2 = l1.^2;
t3 = l2.^2;
t4 = (m2.*t3)./4.0;
t5 = l3.^2;
t6 = (m3.*t5)./4.0;
t7 = q2+q3;
t8 = cos(t7);
t9 = cos(q2);
t10 = (l1.*l2.*m2.*t9)./2.0;
t11 = t4+t6+t10-(l1.*l3.*m3.*t8)./2.0;
t12 = l3-l1.*t8.*2.0;
t13 = (l3.*m3.*t12)./4.0;
t14 = empty+t6;
m = [t4+t6+(m1.*t2)./3.0+m2.*t2+m3.*t2+l1.*l2.*m2.*t9-l1.*l3.*m3.*t8;t11;t13;t11;empty+t6+(m2.*t3)./3.0;t14;t13;t14;empty+(m3.*t5)./3.0];
if nargout > 1
    mi = [1.0;2.0;3.0;4.0;5.0;6.0;7.0;8.0;9.0];
end
if nargout > 2
    t15 = sin(q1);
    t16 = sin(t7);
    t17 = dq2.^2;
    t18 = sin(q2);
    t19 = q1+q2;
    t20 = sin(t19);
    t21 = q1+q2+q3;
    t22 = sin(t21);
    t23 = (g.*l3.*m3.*t22)./2.0;
    t24 = dq1.^2;
    t25 = (l1.*l2.*m2.*t18)./2.0;
    t26 = (l1.*l3.*m3.*t16)./2.0;
    t27 = -t25+t26;
    t28 = l1.*l3.*m3.*t16;
    t29 = cos(q1);
    t30 = cos(t21);
    t31 = cos(t19);
    t32 = l2.*m1.*t31;
    t33 = (g.*l3.*m3.*t30)./2.0;
    t34 = dq3.^2;
    f = [t23-g.*l1.*m1.*t15.*(3.0./2.0)-g.*l1.*m3.*t15-(g.*l2.*m1.*t20)./2.0+(l1.*l2.*m2.*t17.*t18)./2.0-(l1.*l3.*m3.*t16.*t17)./2.0-(l1.*l3.*m3.*t16.*t34)./2.0+dq1.*dq2.*l1.*l2.*m2.*t18-dq1.*dq2.*l1.*l3.*m3.*t16-dq1.*dq3.*l1.*l3.*m3.*t16-dq2.*dq3.*l1.*l3.*m3.*t16;t23+u1-t24.*(t25-(l1.*l3.*m3.*t16)./2.0)-(g.*l2.*m1.*t20)./2.0;t23+u2+(l1.*l3.*m3.*t16.*t24)./2.0];
end
if nargout > 3
    fi = [1.0;2.0;3.0];
end
if nargout > 4
    mz = [t28-l1.*l2.*m2.*t18;t27;t26;t27;t26;t28;t26;t26;t26;t26];
end
if nargout > 5
    mzi = [1.9e1;2.0e1;2.1e1;2.2e1;2.5e1;2.8e1;2.9e1;3.0e1;3.1e1;3.4e1];
end
if nargout > 6
    mzd = [3.0,3.0,9.0];
end
if nargout > 7
    t35 = g.*t30;
    t36 = l1.*t8.*t24;
    t37 = t35+t36;
    t38 = (l3.*m3.*t37)./2.0;
    t39 = dq2.*l3.*m3.*t16;
    t40 = dq3.*l3.*m3.*t16;
    t41 = empty+1.0;
    fz = [g.*(t32+l1.*m1.*t29.*3.0+l1.*m3.*t29.*2.0-l3.*m3.*t30).*(-1.0./2.0);g.*(t32-l3.*m3.*t30).*(-1.0./2.0);t33;t33-(g.*l2.*m1.*t31)./2.0+(l1.*l2.*m2.*t9.*t17)./2.0-(l1.*l3.*m3.*t8.*t17)./2.0-(l1.*l3.*m3.*t8.*t34)./2.0+dq1.*dq2.*l1.*l2.*m2.*t9-dq1.*dq2.*l1.*l3.*m3.*t8-dq1.*dq3.*l1.*l3.*m3.*t8-dq2.*dq3.*l1.*l3.*m3.*t8;t33-(g.*l2.*m1.*t31)./2.0-(l1.*l2.*m2.*t9.*t24)./2.0+(l1.*l3.*m3.*t8.*t24)./2.0;t38;l3.*m3.*(-t35+l1.*t8.*t17+l1.*t8.*t34+dq1.*dq2.*l1.*t8.*2.0+dq1.*dq3.*l1.*t8.*2.0+dq2.*dq3.*l1.*t8.*2.0).*(-1.0./2.0);t38;t38;-l1.*(t39+t40-dq2.*l2.*m2.*t18);-dq1.*l1.*(l2.*m2.*t18-l3.*m3.*t16);dq1.*l1.*l3.*m3.*t16;-l1.*(t39+t40-dq1.*l2.*m2.*t18+dq1.*l3.*m3.*t16-dq2.*l2.*m2.*t18);-l1.*l3.*m3.*t16.*(dq1+dq2+dq3);t41;t41];
end
if nargout > 8
    fzi = [4.0;5.0;6.0;7.0;8.0;9.0;1.0e1;1.1e1;1.2e1;1.3e1;1.4e1;1.5e1;1.6e1;1.9e1;2.3e1;2.7e1];
end
if nargout > 9
    fzd = [3.0,1.0,9.0];
end
