function [p1,p1e,p2,p2e,p3,p3e,v1,v2,v3] = autoGen_monkeyKinematics(q1,q2,q3,dq1,dq2,dq3,m1,m2,m3,g,l1,l2,l3)
%AUTOGEN_MONKEYKINEMATICS
%    [P1,P1E,P2,P2E,P3,P3E,V1,V2,V3] = AUTOGEN_MONKEYKINEMATICS(Q1,Q2,Q3,DQ1,DQ2,DQ3,M1,M2,M3,G,L1,L2,L3)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    26-Nov-2019 23:22:57

t2 = sin(q1);
t3 = cos(q1);
p1 = [(l1.*t2)./2.0;l1.*t3.*(-1.0./2.0)];
if nargout > 1
    t4 = l1.*t2;
    p1e = [t4;-l1.*t3];
end
if nargout > 2
    t5 = q1+q2;
    t6 = sin(t5);
    t7 = cos(t5);
    p2 = [t4+(l2.*t6)./2.0;-l1.*t3-(l2.*t7)./2.0];
end
if nargout > 3
    p2e = [t4+l2.*t6;-l1.*t3-l2.*t7];
end
if nargout > 4
    t8 = q1+q2+q3;
    t9 = sin(t8);
    t10 = cos(t8);
    p3 = [t4-(l3.*t9)./2.0;-l1.*t3+(l3.*t10)./2.0];
end
if nargout > 5
    p3e = [t4-l3.*t9;-l1.*t3+l3.*t10];
end
if nargout > 6
    v1 = [(dq1.*l1.*t3)./2.0;(dq1.*l1.*t2)./2.0];
end
if nargout > 7
    t11 = dq1+dq2;
    t12 = dq1.*l1.*t3;
    t13 = dq1.*l1.*t2;
    v2 = [t12+(l2.*t7.*t11)./2.0;t13+(l2.*t6.*t11)./2.0];
end
if nargout > 8
    t14 = dq1+dq2+dq3;
    v3 = [t12-(l2.*t10.*t14)./2.0;t13-(l2.*t9.*t14)./2.0];
end
