function [f,fz,fzi] = autoGen_obj_torqueSquared(u1,u2)
%AUTOGEN_OBJ_TORQUESQUARED
%    [F,FZ,FZI] = AUTOGEN_OBJ_TORQUESQUARED(U1,U2,U3,U4,U5)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    26-Nov-2019 22:58:46

f = u1.^2+u2.^2;
if nargout > 1
    fz = [u1.*2.0;u2.*2.0];
end
if nargout > 2
    fzi = [8.0;9.0];
end
