function [U,T] = autoGen_monkeyEnergy(q1,q2,q3,dq1,dq2,dq3,m1,m2,m3,g,l1,l2,l3)
%AUTOGEN_MONKEYENERGY
%    [U,T] = AUTOGEN_MONKEYENERGY(Q1,Q2,Q3,DQ1,DQ2,DQ3,M1,M2,M3,G,L1,L2,L3)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    26-Nov-2019 23:22:57

t2 = cos(q1);
t3 = l1.*t2;
t4 = q1+q2;
t5 = cos(t4);
t7 = dq1+dq2;
t12 = dq1.*l1.*t2;
t6 = t12+(l2.*t5.*t7)./2.0;
t11 = sin(q1);
t16 = dq1.*l1.*t11;
t8 = t16+(l2.*t7.*sin(t4))./2.0;
t9 = dq1.^2;
t10 = l1.^2;
t13 = q1+q2+q3;
t14 = cos(t13);
U = -g.*m2.*(t3+(l2.*t5)./2.0)-g.*m3.*(t3-(l3.*t14)./2.0)-(g.*l1.*m1.*t2)./2.0;
if nargout > 1
    t17 = dq1+dq2+dq3;
    t15 = t12-(l2.*t14.*t17)./2.0;
    t18 = t16-(l2.*t17.*sin(t13))./2.0;
    T = (m1.*((t2.^2.*t9.*t10)./4.0+(t9.*t10.*t11.^2)./4.0))./2.0+(m2.*(t6.^2+t8.^2))./2.0+(m3.*(t15.^2+t18.^2))./2.0+(dq2.^2.*l2.^2.*m2)./2.4e1+(dq3.^2.*l3.^2.*m3)./2.4e1+(m1.*t9.*t10)./2.4e1;
end
