function [f,fz,fzi] = haha(u1,u2)
%HAHA
%    [F,FZ,FZI] = HAHA(U1,U2)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    26-Nov-2019 22:58:46

f = u1.^2+u2.^2;
if nargout > 1
    fz = [u1.*2.0;u2.*2.0];
end
if nargout > 2
    fzi = [8.0;9.0];
end
