function ddthetalist = ForwardDynamics_sym(thetalist, dthetalist, taulist, ...
                                       g, Ftip, Mlist, Glist, Slist)


ddthetalist = MassMatrix_sym(thetalist, Mlist, Glist, Slist) ...
              \ (taulist - VelQuadraticForces_sym(thetalist, dthetalist, ...
                                              Mlist, Glist, Slist) ...
                 - GravityForces_sym(thetalist, g, Mlist, Glist, Slist) ...
                 - EndEffectorForces_sym(thetalist, Ftip, Mlist, Glist, ...
                                     Slist));
end